List<Map<String, dynamic>> dummyOrders = [
  {
    "id": 1,
    "orderId": "#ORD-1001",
    "name": "Rahul Sharma",
    "product": "Wireless Bluetooth Earbuds Pro",
    "price": 2598,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "10 Mar 2026",
    "paymenttype": "COD",
    "address": "Jaipur Rajasthan",
    "status": "new",
  },
  {
    "id": 2,
    "orderId": "#ORD-1002",
    "name": "Amit Singh",
    "product": "Smart Watch",
    "price": 3999,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "09 Mar 2026",
    "paymenttype": "Online",
    "address": "Delhi",
    "status": "Packed",
  },
  {
    "id": 3,
    "orderId": "#ORD-1003",
    "name": "Suresh Kumar",
    "product": "Bluetooth Speaker",
    "price": 1899,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "08 Mar 2026",
    "paymenttype": "COD",
    "address": "Mumbai",
    "status": "Shipped",
  },
  {
    "id": 4,
    "orderId": "#ORD-1004",
    "name": "Vikas Sharma",
    "product": "Gaming Mouse",
    "price": 1499,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "07 Mar 2026",
    "paymenttype": "Online",
    "address": "Delhi",
    "status": "Delivered",
  },
  {
    "id": 5,
    "orderId": "#ORD-1005",
    "name": "Rohit Singh",
    "product": "Laptop Stand",
    "price": 899,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "06 Mar 2026",
    "paymenttype": "COD",
    "address": "Jaipur",
    "status": "cancelled",
  },
  {
    "id": 6,
    "orderId": "#ORD-1006",
    "name": "Deepak Verma",
    "product": "Wireless Keyboard",
    "price": 1799,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "05 Mar 2026",
    "paymenttype": "Online",
    "address": "Udaipur",
    "status": "new",
  },
  {
    "id": 7,
    "orderId": "#ORD-1007",
    "name": "Manoj Gupta",
    "product": "USB-C Fast Charger",
    "price": 699,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "04 Mar 2026",
    "paymenttype": "COD",
    "address": "Kota",
    "status": "Packed",
  },
  {
    "id": 8,
    "orderId": "#ORD-1008",
    "name": "Ankit Jain",
    "product": "Noise Cancelling Headphones",
    "price": 5499,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "03 Mar 2026",
    "paymenttype": "Online",
    "address": "Indore",
    "status": "Shipped",
  },
  {
    "id": 9,
    "orderId": "#ORD-1009",
    "name": "Ravi Mehta",
    "product": "Laptop Cooling Pad",
    "price": 1299,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "02 Mar 2026",
    "paymenttype": "COD",
    "address": "Bhopal",
    "status": "Delivered",
  },
  {
    "id": 10,
    "orderId": "#ORD-1010",
    "name": "Pankaj Yadav",
    "product": "Portable Power Bank",
    "price": 1999,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "01 Mar 2026",
    "paymenttype": "Online",
    "address": "Lucknow",
    "status": "cancelled",
  },
  {
    "id": 11,
    "orderId": "#ORD-1011",
    "name": "Sanjay Kumar",
    "product": "Bluetooth Neckband",
    "price": 1299,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "28 Feb 2026",
    "paymenttype": "COD",
    "address": "Delhi",
    "status": "new",
  },
  {
    "id": 12,
    "orderId": "#ORD-1012",
    "name": "Arjun Singh",
    "product": "Smart LED Bulb",
    "price": 499,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "27 Feb 2026",
    "paymenttype": "Online",
    "address": "Jaipur",
    "status": "Packed",
  },
  {
    "id": 13,
    "orderId": "#ORD-1013",
    "name": "Karan Malhotra",
    "product": "Gaming Headset",
    "price": 2599,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "26 Feb 2026",
    "paymenttype": "COD",
    "address": "Chandigarh",
    "status": "Shipped",
  },
  {
    "id": 14,
    "orderId": "#ORD-1014",
    "name": "Mohit Sharma",
    "product": "Wireless Mouse",
    "price": 799,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "25 Feb 2026",
    "paymenttype": "Online",
    "address": "Gurgaon",
    "status": "Delivered",
  },
  {
    "id": 15,
    "orderId": "#ORD-1015",
    "name": "Nitin Agarwal",
    "product": "Type-C Data Cable",
    "price": 299,
    "image": "image/imageasstes/wirelessheadphone.png",
    "orderdate": "24 Feb 2026",
    "paymenttype": "COD",
    "address": "Noida",
    "status": "cancelled",
  },
];
